apiVersion: v1
kind: Service
metadata:
  name: {{ include "brookside.fullname" . }}
  labels:
    {{- include "brookside.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "brookside.selectorLabels" . | nindent 4 }}
