name: "\U0001F41B Bug Report"
description: Report a reproducible problem
labels: [bug]
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible.
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction steps
      description: "How do we trigger the bug?"
      placeholder: |
        1. Go to '...'
        2. Run '...'
        3. Observe the failure
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: |
        OS, Python version, package versions, and any other relevant information.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
