"""Deprecated constants module.

This module previously pulled configuration directly from ``os.environ``.
It now simply re-exports values from :mod:`src.config` for backward
compatibility.  New code should import :data:`settings` from
``src.config`` instead of importing constants here.
"""

from __future__ import annotations

from .config import settings

# AI Providers
OPENAI_API_KEY = settings.OPENAI_API_KEY

# CRM & Marketing Platforms
CRM_API_URL = settings.CRM_API_URL
CRM_API_KEY = settings.CRM_API_KEY
MONDAY_API_TOKEN = settings.MONDAY_API_TOKEN
MONDAY_API_URL = settings.MONDAY_API_URL
HUBSPOT_API_KEY = settings.HUBSPOT_API_KEY
DYNAMICS_TENANT_ID = settings.DYNAMICS_TENANT_ID
DYNAMICS_CLIENT_ID = settings.DYNAMICS_CLIENT_ID
DYNAMICS_CLIENT_SECRET = settings.DYNAMICS_CLIENT_SECRET
DYNAMICS_API_URL = settings.DYNAMICS_API_URL
SF_CLIENT_ID = settings.SF_CLIENT_ID
SF_CLIENT_SECRET = settings.SF_CLIENT_SECRET
SF_USERNAME = settings.SF_USERNAME
SF_PASSWORD = settings.SF_PASSWORD
SF_SECURITY_TOKEN = settings.SF_SECURITY_TOKEN
SF_DOMAIN = settings.SF_DOMAIN

# Advertising & Social Platforms
FACEBOOK_ACCESS_TOKEN = settings.FACEBOOK_ACCESS_TOKEN
GOOGLE_ADS_API_KEY = settings.GOOGLE_ADS_API_KEY

# Real Estate APIs
MLS_API_URL = settings.MLS_API_URL
MLS_API_KEY = settings.MLS_API_KEY
RE_LEADS_API_URL = settings.RE_LEADS_API_URL
RE_LEADS_API_KEY = settings.RE_LEADS_API_KEY
LISTING_POST_API_URL = settings.LISTING_POST_API_URL
LISTING_POST_API_KEY = settings.LISTING_POST_API_KEY

# Document Signing
DOCUSIGN_ACCESS_TOKEN = settings.DOCUSIGN_ACCESS_TOKEN
DOCUSIGN_INTEGRATOR_KEY = settings.DOCUSIGN_INTEGRATOR_KEY
DOCUSIGN_USER_ID = settings.DOCUSIGN_USER_ID
DOCUSIGN_ACCOUNT_ID = settings.DOCUSIGN_ACCOUNT_ID
DOCUSIGN_BASE_URL = settings.DOCUSIGN_BASE_URL

# Storage & Infrastructure
AWS_ACCESS_KEY_ID = settings.AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY = settings.AWS_SECRET_ACCESS_KEY
AWS_S3_BUCKET = settings.AWS_S3_BUCKET
AWS_REGION = settings.AWS_REGION
AWS_SNS_TOPIC_ARN = settings.AWS_SNS_TOPIC_ARN
AWS_SES_REGION = settings.AWS_SES_REGION
AZURE_BLOB_CONNECTION_STR = settings.AZURE_BLOB_CONNECTION_STR
AZURE_BLOB_CONTAINER = settings.AZURE_BLOB_CONTAINER
GCS_BUCKET_NAME = settings.GCS_BUCKET_NAME
GOOGLE_APPLICATION_CREDENTIALS = settings.GOOGLE_APPLICATION_CREDENTIALS
REDIS_URL = settings.REDIS_URL
DB_CONNECTION_STRING = settings.DB_CONNECTION_STRING
KAFKA_BOOTSTRAP_SERVERS = settings.KAFKA_BOOTSTRAP_SERVERS
RABBITMQ_URL = settings.RABBITMQ_URL

# Messaging & Notifications
SENDGRID_API_KEY = settings.SENDGRID_API_KEY
SLACK_WEBHOOK_URL = settings.SLACK_WEBHOOK_URL
TEAMS_WEBHOOK_URL = settings.TEAMS_WEBHOOK_URL
FCM_SERVER_KEY = settings.FCM_SERVER_KEY
PUSHOVER_USER_KEY = settings.PUSHOVER_USER_KEY
PUSHOVER_API_TOKEN = settings.PUSHOVER_API_TOKEN
DISCORD_WEBHOOK_URL = settings.DISCORD_WEBHOOK_URL
TWILIO_ACCOUNT_SID = settings.TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN = settings.TWILIO_AUTH_TOKEN
TWILIO_FROM_PHONE = settings.TWILIO_FROM_PHONE

# Monitoring & Analytics
PROMETHEUS_PUSHGATEWAY = settings.PROMETHEUS_PUSHGATEWAY
GA4_MEASUREMENT_ID = settings.GA4_MEASUREMENT_ID
GA4_API_SECRET = settings.GA4_API_SECRET
MIXPANEL_TOKEN = settings.MIXPANEL_TOKEN
SEGMENT_WRITE_KEY = settings.SEGMENT_WRITE_KEY
AMPLITUDE_API_KEY = settings.AMPLITUDE_API_KEY
IPINFO_TOKEN = settings.IPINFO_TOKEN
UA_PARSER_REGEX_PATH = settings.UA_PARSER_REGEX_PATH

# Data Enrichment
CLEARBIT_API_KEY = settings.CLEARBIT_API_KEY
PEOPLE_DATA_LABS_API_KEY = settings.PEOPLE_DATA_LABS_API_KEY
HUNTER_API_KEY = settings.HUNTER_API_KEY
FULLCONTACT_API_KEY = settings.FULLCONTACT_API_KEY
ZOOMINFO_API_KEY = settings.ZOOMINFO_API_KEY
PIPL_API_KEY = settings.PIPL_API_KEY
SNOVIO_API_KEY = settings.SNOVIO_API_KEY

# Payment Gateways
STRIPE_API_KEY = settings.STRIPE_API_KEY
PAYPAL_CLIENT_ID = settings.PAYPAL_CLIENT_ID
PAYPAL_CLIENT_SECRET = settings.PAYPAL_CLIENT_SECRET
SQUARE_ACCESS_TOKEN = settings.SQUARE_ACCESS_TOKEN
SQUARE_ENVIRONMENT = settings.SQUARE_ENVIRONMENT
BRAINTREE_MERCHANT_ID = settings.BRAINTREE_MERCHANT_ID
BRAINTREE_PUBLIC_KEY = settings.BRAINTREE_PUBLIC_KEY
BRAINTREE_PRIVATE_KEY = settings.BRAINTREE_PRIVATE_KEY
AUTHORIZE_NET_API_LOGIN_ID = settings.AUTHORIZE_NET_API_LOGIN_ID
AUTHORIZE_NET_TRANSACTION_KEY = settings.AUTHORIZE_NET_TRANSACTION_KEY
ADYEN_API_KEY = settings.ADYEN_API_KEY
ADYEN_MERCHANT_ACCOUNT = settings.ADYEN_MERCHANT_ACCOUNT
ADYEN_ENVIRONMENT = settings.ADYEN_ENVIRONMENT
PLAID_CLIENT_ID = settings.PLAID_CLIENT_ID
PLAID_SECRET = settings.PLAID_SECRET
PLAID_ENVIRONMENT = settings.PLAID_ENVIRONMENT

# Utility Services
GOOGLE_TRANSLATE_API_KEY = settings.GOOGLE_TRANSLATE_API_KEY
CONFIG_PATH = settings.CONFIG_PATH
API_AUTH_KEY = settings.API_AUTH_KEY

# Logistics & e-commerce APIs
TMS_API_URL = settings.TMS_API_URL
TMS_API_KEY = settings.TMS_API_KEY
INVENTORY_API_URL = settings.INVENTORY_API_URL
INVENTORY_API_KEY = settings.INVENTORY_API_KEY
ECOMMERCE_API_URL = settings.ECOMMERCE_API_URL
ECOMMERCE_API_KEY = settings.ECOMMERCE_API_KEY
