name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
          pip install mypy
      - name: Run mypy
        run: mypy .
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
      - name: Lint commit message
        run: |
          echo "$(git log -1 --pretty=%B)" > commit_message.txt
          pre-commit run --hook-stage commit-msg --commit-msg-filename commit_message.txt
      - name: Run tests
        run: pytest -q
